name: Test  # The name of the workflow, which will appear in the Actions tab and in the badge URL

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the runner (operating system) for the workflow

    steps:
      - name: Checkout code  # Step to check out the code from the repository
        uses: actions/checkout@v2

      - name: Run tests  # Step to run tests or commands
        run: echo "Running tests"  # Replace this with the actual command you want to run for testing
